name             'composer'
source_url       'https://github.com/apaxsoftware/composer'
issues_url       'https://github.com/apaxsoftware/composer/issues'
maintainer       'Chris Allen'
maintainer_email 'chris@apaxsoftware.com'
license          'Apache-2.0'
description      'Installs and configures composer'
version          '1.0.0'
chef_version     '>= 12.1'

supports         'ubuntu'
